spring.application.name=Alimentacion
server.port=${PORT:8088}

#conecta a la base de datos de jorge "MicroservicioAlimentacion"
spring.datasource.url=jdbc:postgresql://ep-young-brook-ap55kd7c-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_k6RHvan4cEGT

# Configuraci\u00f3n de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.htm
#Url de microservicios que se ocuparan
url.microservicio.criadero=https://microserviciocriadero.onrender.com
url.microservicio.jaula=https://microserviciojaulas.onrender.com